[package]
name = "firefly-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-graphics = "0.8.1"
embedded-graphics-transform = "0.1.0"
embedded-io = { version = "0.6.1", default-features = false }
wasmi = { version = "0.31.2", default-features = false }
